apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-flask-app
  template:
    metadata:
      labels:
        app: hello-flask-app
    spec:
      containers:
        - name: hello-falsk-container
          image: shuklaaayush/hello-python:v2
          ports:
            - containerPort: 5000
