kind: Service
apiVersion: v1
metadata:
  name: hello-flask-service
spec:
  selector:
    app: hello-flask-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30040
